version: "3"

services:
  api:
    build: ./back-end/
    command:  [ "./wait-for-it.sh", 'db', "yarn", "start"] 
    networks:
      - default
      - app-connect
    depends_on:
      - db
    ports:
      - "3333:3333"
    environment:
        POSTGRES_DB: 'todos'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'docker'
  
  web-app:
    build: ./front-end/
    command: ["yarn", "start"]
    networks:
      - default
      - app-connect

    ports:
      - "3000:3000"

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: 'todos'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'docker'
    networks:
      - app-connect
    ports:
      - "5432:5432"

networks:
    default:
    app-connect:
      internal: True